version: '3.3'
services:
  api:
    build: ./api
    container_name: api_backend
    ports:
      - '4000:4000'
    depends_on:
      - db
    volumes:
      - ./api:/app
      - ./app/node_modules
  frontend:
    build: ./frontend
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
  db:
    container_name: postgres
    image: postgres
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
volumes: 
 data: {}